ARG BASE_IMAGE
FROM ${BASE_IMAGE}

RUN deps=''\
  && apt-get update\
  # for route and sudo
  && apt-get install --no-install-recommends -y curl gosu net-tools sudo ${deps}\
  && apt-get purge -y --auto-remove ${deps}\
  && pip3 install cffi minio bottle

RUN mkdir -p /sebs
COPY dockerfiles/kata_fc/python/*.py /sebs/
COPY dockerfiles/kata_fc/python/run_server.sh /sebs/
ENV PYTHONPATH=/sebs/.python_packages/lib/site-packages:$PYTHONPATH

COPY dockerfiles/kata_fc/entrypoint.sh /sebs/entrypoint.sh
RUN chmod +x /sebs/entrypoint.sh

ENTRYPOINT ["/sebs/entrypoint.sh"]
